/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StablecoinMock__factory } from "./StablecoinMock__factory";
export { ValcoreV1__factory } from "./ValcoreV1__factory";
